language: r
warnings_are_errors: true
latex: false
fortran: false
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: oldrel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: release
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: devel
    - os: osx
      osx_image: xcode10.1
      brew_packages: poppler
    - os: osx
      osx_image: xcode9.4
      brew_packages: poppler
    - os: osx
      osx_image: xcode9.2
      brew_packages: poppler
    - os: osx
      osx_image: xcode9.2
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
  
addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data
      - valgrind

cran: https://cran.rstudio.com/
r_packages:
   - covr
   
r_check_args: "--no-vignettes --no-manual --as-cran"
      
after_success:
   - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change  
    
# Prevents Travis timeout for building libpoppler
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
      
